baseURL = "https://awslabs.github.io/aws-cloudfront-extensions/"
languageCode = "en-us"
title = "CloudFront Extensions"
theme = "hugo-theme-learn"
contentDir = "../docs"
canonifyURLs = true

[params]
  themeVariant = "cloudfrontext"
  disableLandingPageButton = true
